language: python
sudo: false
cache: bundler

python:
  - 3.5

addons:
  apt:
    packages:
      - libarchive-dev

install:
  - pip install cffi
  - pip install pytest
  - pip install pytest-xdist

script:
  - make tests
